export const GetTabCompletion = 'Html.getTabCompletion'
export const GetCompletion = 'Html.getCompletion'
export const GetClosingTag = 'Html.getClosingTag'
export const GetDefinition = 'Html.getDefinition'
export const WrapTag = 'Html.wrapTag'
